'use client';

import { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
import { HistoryItem } from '../types';
import Header from './Header';
import ActionButtons from './ActionButtons';
import PromptDisplay from './PromptDisplay';
import HistorySidebar from './HistorySidebar';

const PixelBlast = dynamic(() => import('./PixelBlast'), { 
  ssr: false,
  loading: () => <div className="w-full h-full bg-[var(--background)]" />
});

interface ResultScreenProps {
  generatedPrompt: string;
  modelUsed: string;
  providerUsed: string;
  copied: boolean;
  isGenerating: boolean;
  historyOpen: boolean;
  history: HistoryItem[];
  onCopy: () => void;
  onRegenerate: () => void;
  onBack: () => void;
  onHistoryToggle: () => void;
  onHistoryClose: () => void;
  onHistorySelect: (item: HistoryItem) => void;
}

export default function ResultScreen({
  generatedPrompt,
  modelUsed,
  providerUsed,
  copied,
  isGenerating,
  historyOpen,
  history,
  onCopy,
  onRegenerate,
  onBack,
  onHistoryToggle,
  onHistoryClose,
  onHistorySelect,
}: ResultScreenProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div className="min-h-screen relative" style={{ background: 'var(--background)' }}>
      {/* Background Pixel Animation */}
      <div className="absolute inset-0 w-full h-full pointer-events-none">
        {mounted && (
          <PixelBlast
            variant="circle"
            pixelSize={6}
            color="#8A2BE2"
            patternScale={3}
            patternDensity={1.2}
            pixelSizeJitter={0.5}
            enableRipples
            rippleSpeed={0.4}
            rippleThickness={0.12}
            rippleIntensityScale={1.5}
            liquid
            liquidStrength={0.12}
            liquidRadius={1.2}
            liquidWobbleSpeed={5}
            speed={0.6}
            edgeFade={0.25}
            transparent
          />
        )}
      </div>

      {/* Content */}
      <div className="relative z-10">
        <Header 
          showBackButton 
          onBackClick={onBack}
          showHistoryButton 
          onHistoryClick={onHistoryToggle}
        />
        <main className="mx-auto max-w-5xl px-8 py-8">
          <ActionButtons
            copied={copied}
            onCopy={onCopy}
          />
          <PromptDisplay prompt={generatedPrompt} />
          <div className="flex justify-center gap-4">
            <button
              onClick={onRegenerate}
              disabled={isGenerating}
              className="rounded-lg border border-white/20 bg-white/5 backdrop-blur-sm px-6 py-2 transition-all hover:bg-white/10 hover:shadow-[0_0_15px_rgba(138,43,226,0.3)] cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Regenerate
            </button>
            <button
              onClick={onBack}
              className="rounded-lg border border-white/20 bg-white/5 backdrop-blur-sm px-6 py-2 transition-all hover:bg-white/10 hover:shadow-[0_0_15px_rgba(138,43,226,0.3)] cursor-pointer"
            >
              Go Back to Edit
            </button>
          </div>
          {modelUsed && (
            <div className="mt-6 flex items-center justify-center gap-2 text-sm text-gray-400">
              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" />
              </svg>
              <span>
                Generated by <span className="font-semibold text-white">{providerUsed}</span> using{' '}
                <span className="font-mono text-[var(--primary)]">{modelUsed}</span>
              </span>
            </div>
          )}
        </main>
        <HistorySidebar
          isOpen={historyOpen}
          history={history}
          onClose={onHistoryClose}
          onSelectItem={onHistorySelect}
        />
      </div>
    </div>
  );
}

